# Numpy

## 기본
ndarray : class, 같은 type의 값들로 구성, axis = 차원

### 속성

- ndarray.ndim : 차원수
- ndarray.shape : 데이터 모양
- ndarray.size : 전체 값 개수
- ndarray.dtype : 값의 type
- ndarray.itemsize : 각 값의 크기 (byte)

In [1]:
import numpy as np

ar1= np.arange(15).reshape (3,5)

ar1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [2]:
ar1.shape

(3, 5)

In [3]:
ar1.ndim # 차원

2

In [4]:
ar1.size

15

### 생성

- np.array ( 리스트 ) 
- np.zeros (shape )  or np.ones , np.empty
- np.arrange (size) or np.arange (시작, 끝, 간격) 


In [5]:
np.array ([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [6]:
np.zeros( (3,4) )

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [7]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## Operations

### 기본
- 사칙연산 : 벡터* 스칼라  => 각 element와 스칼라 연산
- 각 element 에 적용되는 연산:  exp(), sqrt() .. 
- 벡터 * 벡터 => 일반 벡터연산이 아니고, 같은 위치의 element 끼리 연산
- 벡터 곱은 @
- += 도 동작함 

In [8]:
A = np.array ( [[1,2], [3,4]])
B = np.array ( [[2,3], [4,5]])

A*4

array([[ 4,  8],
       [12, 16]])

In [9]:
np.sqrt(A)  # 제곱근

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

In [10]:
A*B

array([[ 2,  6],
       [12, 20]])

In [11]:
A.dot(B)  #내적

array([[10, 13],
       [22, 29]])

In [12]:
A@B  #내적

array([[10, 13],
       [22, 29]])

In [13]:
A+=3
A

array([[4, 5],
       [6, 7]])

### sum, max, min

In [14]:
A= np.random.randn(3,2)
A

array([[ 0.61063552, -0.43239738],
       [-0.49210257, -0.06694654],
       [-0.88318534,  0.78979318]])

In [15]:
A.sum()

-0.47420314238685

In [16]:
A.min()

-0.8831853406543112

### (중요) axis에 따른 연산

- 주요 파라메터 : axis, 차원 기준 
- sum (axis=0 ) : 첫번째 차원으로 합(행)
- sum (axis=1 ) : 두번째 차원으로 합(열)

In [17]:
B=np.arange(12).reshape (3,4)  # 첫번째 차원 =3개 element , 두번째 차원 =각기 element 는 4개 짜리 array
B

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [18]:
B.sum (axis=0) # 3개의 element 끼리 더함(행끼리)

array([12, 15, 18, 21])

In [19]:
B.mean (axis=1) # 2번째 차원의 4개의 element 끼리 평균(열끼리)

array([1.5, 5.5, 9.5])

In [20]:
B.max(axis=0)

array([ 8,  9, 10, 11])

## 과제 1 : 1부터 30까지 숫자로 (5,3,2) 3차원을 만든 뒤, 각 숫자에 0과1 사이의 random noise  을 곱한 결과를 출력하시오


과제 실행 위해 필요한 부분 (ex. import numpy as np )만 발췌해서, 답안지만 hw-02.ipynb 파일로 제출 

In [21]:
X=np.arange(1, 31).reshape((5,3,2))
Y= np.random.rand(5,3,2)
X

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]],

       [[13, 14],
        [15, 16],
        [17, 18]],

       [[19, 20],
        [21, 22],
        [23, 24]],

       [[25, 26],
        [27, 28],
        [29, 30]]])

In [22]:
Y

array([[[0.56125913, 0.0188493 ],
        [0.85662273, 0.52368256],
        [0.28263402, 0.93273533]],

       [[0.83195564, 0.13034663],
        [0.04301526, 0.59584405],
        [0.62332437, 0.24156076]],

       [[0.99855929, 0.80998027],
        [0.19248632, 0.38144718],
        [0.8008952 , 0.2460893 ]],

       [[0.02592661, 0.08623564],
        [0.02598456, 0.36481938],
        [0.9737828 , 0.28498725]],

       [[0.82745117, 0.17778734],
        [0.47437481, 0.65482838],
        [0.87344399, 0.32056093]]])

In [23]:
X*Y

array([[[ 0.56125913,  0.0376986 ],
        [ 2.56986819,  2.09473023],
        [ 1.41317009,  5.59641198]],

       [[ 5.82368947,  1.04277306],
        [ 0.38713737,  5.95844047],
        [ 6.85656811,  2.89872914]],

       [[12.98127077, 11.33972379],
        [ 2.8872948 ,  6.10315488],
        [13.6152184 ,  4.42960743]],

       [[ 0.49260551,  1.72471288],
        [ 0.5456758 ,  8.02602631],
        [22.39700448,  6.83969401]],

       [[20.68627936,  4.62247089],
        [12.80811998, 18.33519463],
        [25.32987579,  9.61682785]]])

## Indexing, slicing


- 1차원 : element A[2],  범위 A[2:5]
- 2차원 : element B[2,3] , 범위 B [1:3, : ]   : 는 전체를 의미
- ...  :  x[1, 2, ...]  동일  x[1, 2, :, :, :]

In [24]:
A=np.arange (5, 15, 1)  #1차원
A

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [25]:
A[[2,3]]

array([7, 8])

In [26]:
A[1:3]

array([6, 7])

In [27]:
B=np.arange(30).reshape((5,6))  #2차원
B

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [28]:
B[3,2]

20

In [29]:
B[3, 2:4]

array([20, 21])

In [30]:
C=np.arange(45).reshape((5,3,3))
C

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]],

       [[27, 28, 29],
        [30, 31, 32],
        [33, 34, 35]],

       [[36, 37, 38],
        [39, 40, 41],
        [42, 43, 44]]])

In [31]:
C[:,:,1]

array([[ 1,  4,  7],
       [10, 13, 16],
       [19, 22, 25],
       [28, 31, 34],
       [37, 40, 43]])

In [32]:
C[...,1]  #컬럼

array([[ 1,  4,  7],
       [10, 13, 16],
       [19, 22, 25],
       [28, 31, 34],
       [37, 40, 43]])

## 과제 2 : np.arange(30).reshape((5,6)) 에서 짝수 컬럼 (0,2,4..) column 만 뽑아서 새로운 array를 만드시오

In [33]:
X = np.arange(30).reshape((5,6))
X

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [34]:
X[:,0::2]

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16],
       [18, 20, 22],
       [24, 26, 28]])

...

# Pandas

## dataframe 

2차원 구조, column 마다 다른 데이터 type, 일반 csv 데이터 구조 처리에 적합

### 만들기

- 딕셔너리로부터 만들기  :  {'컬럼명': [ 값, 값,.. ], '컬럼명': [값, 값, .. ] }
   pd.DataFrame (딕셔너리) 
   
- index와 column label (컬럼명)


In [35]:
#pip install pandas

Note: you may need to restart the kernel to use updated packages.


In [36]:
import pandas as pd

dic= { 'gender' : [ 1, 2, 1, 2], 'bloodtype': ["A", "B", "O", "AB"]}

df1= pd.DataFrame(dic)

df1

gender bloodtype
0       1         A
1       2         B
2       1         O
3       2        AB

- numpy array를 사용 가능 

  DataFrame ( array, index=index array, columns = 컬럼명)

In [37]:
dates = pd.date_range("20210309", periods=6)  # 날짜 생성
dates

DatetimeIndex(['2021-03-09', '2021-03-10', '2021-03-11', '2021-03-12',
               '2021-03-13', '2021-03-14'],
              dtype='datetime64[ns]', freq='D')

In [38]:
df = pd.DataFrame(np.random.randn(6, 4), index=dates, columns=list("ABCD"))
df

A         B         C         D
2021-03-09 -0.335582 -0.132845 -1.207005  1.409560
2021-03-10 -0.535366 -0.188766 -0.031210  0.185986
2021-03-11  0.254863 -0.558857 -1.396600 -0.717114
2021-03-12  1.555864  0.032306  1.964043 -0.458853
2021-03-13 -0.560026  2.494168  0.805430  1.514611
2021-03-14  1.119716 -0.771549 -0.111551  1.011749

### 보기

In [39]:
df.head()

A         B         C         D
2021-03-09 -0.335582 -0.132845 -1.207005  1.409560
2021-03-10 -0.535366 -0.188766 -0.031210  0.185986
2021-03-11  0.254863 -0.558857 -1.396600 -0.717114
2021-03-12  1.555864  0.032306  1.964043 -0.458853
2021-03-13 -0.560026  2.494168  0.805430  1.514611

In [40]:
df.tail(2)

A         B         C         D
2021-03-13 -0.560026  2.494168  0.805430  1.514611
2021-03-14  1.119716 -0.771549 -0.111551  1.011749

In [41]:
df.index

DatetimeIndex(['2021-03-09', '2021-03-10', '2021-03-11', '2021-03-12',
               '2021-03-13', '2021-03-14'],
              dtype='datetime64[ns]', freq='D')

In [42]:
df.columns

Index(['A', 'B', 'C', 'D'], dtype='object')

- 간단한 통계

In [43]:
df.describe()

A         B         C         D
count  6.000000  6.000000  6.000000  6.000000
mean   0.249911  0.145743  0.003851  0.490990
std    0.903057  1.187886  1.259116  0.960990
min   -0.560026 -0.771549 -1.396600 -0.717114
25%   -0.485420 -0.466334 -0.933142 -0.297643
50%   -0.040360 -0.160805 -0.071381  0.598867
75%    0.903503 -0.008982  0.596270  1.310108
max    1.555864  2.494168  1.964043  1.514611

- sort

In [44]:
df.sort_values(by="B")  #B를 기준으로 sorting

A         B         C         D
2021-03-14  1.119716 -0.771549 -0.111551  1.011749
2021-03-11  0.254863 -0.558857 -1.396600 -0.717114
2021-03-10 -0.535366 -0.188766 -0.031210  0.185986
2021-03-09 -0.335582 -0.132845 -1.207005  1.409560
2021-03-12  1.555864  0.032306  1.964043 -0.458853
2021-03-13 -0.560026  2.494168  0.805430  1.514611

### csv 파일 읽기

read_csv(파일명)

In [45]:
import pandas as pd
df=pd.read_csv("studentlist.csv", encoding="cp949")
df

name sex  age  grade absence bloodtype  height  weight  dept
0   김길동  남자   23      3       유         O   165.3    68.2     2
1   이미린  여자   22      2       무        AB   170.1    53.0     3
2   홍길동  남자   24      4       무         B   175.0    80.1     1
3   김철수  남자   23      3       무        AB   182.1    85.7     2
4   손세수  여자   20      1       유         A   168.0    49.5     1
5   박미희  여자   21      2       무         O   162.0    52.0     3
6   강수친  여자   22      1       무         O   155.2    45.3     2
7   이희수  여자   23      1       무         A   176.9    55.0     1
8   이철린  남자   23      3       무         B   178.5    64.2     1
9   방희철  남자   22      2       무         B   176.1    61.3     3
10  박수호  남자   24      4       유         O   167.1    62.0     3
11  임동민  남자   22      2       무        AB   180.0    75.8     3
12  김민수  남자   21      1       무         A   162.2    55.3     1
13  이희진  여자   23      3       무         O   176.1    53.1     2
14  김미진  여자   22      2       무         B   158.2    45.2     3
15  김동수  남자   24      4       유         B   168.6    70.2     1
16  여수근  남자   21      1       무         A   169.2    62.2     2

### indexing, selection

In [46]:
df[0:3]  # rows

name sex  age  grade absence bloodtype  height  weight  dept
0  김길동  남자   23      3       유         O   165.3    68.2     2
1  이미린  여자   22      2       무        AB   170.1    53.0     3
2  홍길동  남자   24      4       무         B   175.0    80.1     1

In [47]:
df[["age", "grade"]]  # column

age  grade
0    23      3
1    22      2
2    24      4
3    23      3
4    20      1
5    21      2
6    22      1
7    23      1
8    23      3
9    22      2
10   24      4
11   22      2
12   21      1
13   23      3
14   22      2
15   24      4
16   21      1

- index에 의한 참조 : iloc

In [48]:
df.iloc[1:5, 0:3]  

name sex  age
1  이미린  여자   22
2  홍길동  남자   24
3  김철수  남자   23
4  손세수  여자   20

In [49]:
df.iloc[ [1,2,4], [0, 2]]

name  age
1  이미린   22
2  홍길동   24
4  손세수   20

- label에 의한 참조 : loc

In [50]:
df.loc[0:3, ["age","grade"]]  

age  grade
0   23      3
1   22      2
2   24      4
3   23      3

- 값에 의한 참조 : boolean indexing , 조건에 맞는 row를 선택

In [51]:
df.describe()

age      grade      height     weight       dept
count  17.000000  17.000000   17.000000  17.000000  17.000000
mean   22.352941   2.294118  170.035294  61.064706   2.000000
std     1.169464   1.104802    7.849756  11.851685   0.866025
min    20.000000   1.000000  155.200000  45.200000   1.000000
25%    22.000000   1.000000  165.300000  53.000000   1.000000
50%    22.000000   2.000000  169.200000  61.300000   2.000000
75%    23.000000   3.000000  176.100000  68.200000   3.000000
max    24.000000   4.000000  182.100000  85.700000   3.000000

In [52]:
df["bloodtype"]=="B"

0     False
1     False
2      True
3     False
4     False
5     False
6     False
7     False
8      True
9      True
10    False
11    False
12    False
13    False
14     True
15     True
16    False
Name: bloodtype, dtype: bool

In [53]:
df[ df["bloodtype"]=="B"]

name sex  age  grade absence bloodtype  height  weight  dept
2   홍길동  남자   24      4       무         B   175.0    80.1     1
8   이철린  남자   23      3       무         B   178.5    64.2     1
9   방희철  남자   22      2       무         B   176.1    61.3     3
14  김미진  여자   22      2       무         B   158.2    45.2     3
15  김동수  남자   24      4       유         B   168.6    70.2     1

In [54]:
df.loc [df["bloodtype"].isin( ["B", "A"] ), ["name", "age"] ]

name  age
2   홍길동   24
4   손세수   20
7   이희수   23
8   이철린   23
9   방희철   22
12  김민수   21
14  김미진   22
15  김동수   24
16  여수근   21

### operations

- 평균 등 : 객체.함수()

In [55]:
df['height'].mean()

170.03529411764703

## 과제 3 : 혈액형이 B형인 사람의 키의 평균을 구하시오

In [56]:
df.loc[df["bloodtype"].isin( ["B"]),["height"]]

height
2    175.0
8    178.5
9    176.1
14   158.2
15   168.6

In [57]:
groupA = df.groupby('bloodtype')['height'].mean()
groupA

bloodtype
A     169.075
AB    177.400
B     171.280
O     165.140
Name: height, dtype: float64

In [58]:
groupA["B"]

171.28

In [59]:
groupB = df[(df["bloodtype"]=="B")].mean()
groupB

age        23.00
grade       3.00
height    171.28
weight     64.20
dept        1.80
dtype: float64

In [60]:
groupB['height']

171.28