# 01 파이썬 리뷰

## 파일 읽기 

In [5]:
# -*- coding: utf-8 -*-

fd=open("studentlist.txt")

line = fd.readline() # 기준 
lines = fd.readlines()

print(line)
print ("line# : ", len(lines))

name,sex,age,grade,absence,bloodtype,height,weight,dept

line# :  17


## 필드 분할, type 가공

In [6]:
Table=[] # 전체 레코드를 담은 테이블 

for line in lines :  # 한 줄 씩  line 변수에 담아서
    
    fields= line.split(",") # , 를 기준으로 나눈다. -> fields라는 list가 만들어진다.
    # name,sex,age,grade,absence,bloodtype,height,weight,dept
    #  0    1   2    3    4        5         6     7      8

    fields[2] = int(fields[2])  # 나이를 숫자로 바꿔 넣기

    fields[6] = float(fields[6])  # 키를 숫자로 바꿔 넣기 
    fields[7] = float(fields[7])  # 몸무게도 
    fields[8] = fields[8].strip()
          
    Table.append(fields)  #레코드를 테이블에 추가 

print (Table[1:3])

[['이미린', '여자', 22, '2', '무', 'AB', 170.1, 53.0, '03'], ['홍길동', '남자', 24, '4', '무', 'B', 175.0, 80.1, '01']]


## 정렬

In [4]:
Table= sorted(Table, key = lambda con : con[2]) # 나이로 정렬
for record in Table :
    print (record[0], record[1], record[2])

손세수 여자 20
박미희 여자 21
김민수 남자 21
여수근 남자 21
이미린 여자 22
강수친 여자 22
방희철 남자 22
임동민 남자 22
김미진 여자 22
김길동 남자 23
김철수 남자 23
이희수 여자 23
이철린 남자 23
이희진 여자 23
홍길동 남자 24
박수호 남자 24
김동수 남자 24


## 기술 통계 : 평균 구하기, 키 평균

In [5]:
heightSum=0
for rec in Table :
    height= rec[6]
    heightSum+=height

print (heightSum / len(Table))

170.03529411764706


## 기술통계 :  도수 구하기 

### 학과 별 학생 수 

In [6]:
dept_dic= {}  # {학과 코드: 도수}
for rec in Table :
    dept_code=rec[8]
    if dept_code in dept_dic:
        dept_dic[dept_code]+=1
    else :
        dept_dic[dept_code]=1

print (dept_dic)

{'01': 6, '03': 6, '02': 5}


## join 
### 학과 코드 파일 읽어서 도수 결과에 표기

In [7]:
deptcode={}  # {학과 코드 : 실제 명칭}

f=open("deptcode.txt") 
for line in f:
    code, name=line.split(",")
    deptcode[code]=name.strip()
    #print (deptcode)

for key, value in dept_dic.items():
    print (deptcode[key], value)


소프트웨어 6
통계보험 6
AI융합 5


## group by :  혈액형 별 키 평균

### 혈액형 별 키 합계, 도수 집계  

In [8]:
b_table={}  # 집계 테이블 : { 혈액형 : [합계, 도수] }

for rec in Table :
    bloodtype=rec[5]
    if bloodtype in b_table:  # 진료과목이 있는지
        b_table[bloodtype]= [ b_table[bloodtype][0]+rec[6], b_table[bloodtype][1]+ 1]  # 키 합계, 갯수 
    else:
        b_table[bloodtype]= [rec[6], 1]  # 키 , 갯수 

print ( b_table)

{'A': [676.3, 4], 'O': [825.7, 5], 'AB': [532.2, 3], 'B': [856.4, 5]}


In [9]:
for key, value in b_table.items():
    print ( key , value[0]/value[1] )

A 169.075
O 165.14000000000001
AB 177.4
B 171.28


## *과제 1 : 성별, 혈액형 별 몸무게의 평균

결과예시)

남자, A, 얼마

남자, B, 얼마

### 제출방법 

test1.ipynb 파일 제출 (위 내용 포함)  

In [10]:
#20160356 김준용
Table= sorted(Table, key = lambda con : (con[1],con[5]) ) # 성별, 혈액형으로 정렬
for record in Table :
    print ( record[0], record[1], record[5], record[7])

김민수 남자 A 55.3
여수근 남자 A 62.2
임동민 남자 AB 75.8
김철수 남자 AB 85.7
방희철 남자 B 61.3
이철린 남자 B 64.2
홍길동 남자 B 80.1
김동수 남자 B 70.2
김길동 남자 O 68.2
박수호 남자 O 62.0
손세수 여자 A 49.5
이희수 여자 A 55.0
이미린 여자 AB 53.0
김미진 여자 B 45.2
박미희 여자 O 52.0
강수친 여자 O 45.3
이희진 여자 O 53.1


In [11]:
#20160356 김준용
Result_table = {}  #{ 성별 : { 혈액형 : [합계, 도수] } }
m_table = {}  #남자 딕셔너리
w_table = {}  #여자 딕셔너리

for rec in Table :
    sextype = rec[1]
    if sextype in "남자":
        bloodtype=rec[5]
        if bloodtype in m_table:  # 진료과목이 있는지
            m_table[bloodtype]= [ m_table[bloodtype][0]+rec[7], m_table[bloodtype][1]+ 1]  # 몸무게 합계, 갯수 
        else:
            m_table[bloodtype]= [rec[7], 1]  # 몸무게 , 갯수
        Result_table[sextype] = m_table
    else:
        bloodtype=rec[5]
        if bloodtype in w_table:  # 진료과목이 있는지
            w_table[bloodtype]= [ w_table[bloodtype][0]+rec[7], w_table[bloodtype][1]+ 1]  # 몸무게 합계, 갯수 
        else:
            w_table[bloodtype]= [rec[7], 1]  # 몸무게 , 갯수
        Result_table[sextype] = w_table

print(Result_table)

{'남자': {'A': [117.5, 2], 'AB': [161.5, 2], 'B': [275.8, 4], 'O': [130.2, 2]}, '여자': {'A': [104.5, 2], 'AB': [53.0, 1], 'B': [45.2, 1], 'O': [150.4, 3]}}


In [16]:
#20160356 김준용
for key, value in m_table.items():
    print ( list(Result_table.keys())[0], key , value[0]/value[1] )
for key, value in w_table.items():
    print ( list(Result_table.keys())[1], key , round(value[0]/value[1], 2) )

남자 A 58.75
남자 AB 80.75
남자 B 68.95
남자 O 65.1
여자 A 52.25
여자 AB 53.0
여자 B 45.2
여자 O 50.13


In [25]:
result_table={}

for rec in Table:
    sex = rec[1]
    bloodtype = rec[5]
    #s_b_type = f'{sex}, bloodtype'
    s_b_type = f'{sex}, {bloodtype}'
    if s_b_type in result_table:
        result_table[s_b_type] = [result_table[s_b_type][0]+rec[7], result_table[s_b_type][1]+ 1]
    else:
        result_table[s_b_type] = [rec[7], 1]
    
for key, value in result_table.items():
    print (key[0], key[1], value[0]/value[1] )

남 자 58.75
남 자 80.75
남 자 68.95
남 자 65.1
여 자 52.25
여 자 53.0
여 자 45.2
여 자 50.13333333333333


In [1]:
import numpy as np
A = np.array( [[1,2], [3,4]])
B = np.array ( [[2,3], [4,5]])
A+=3
print(A)
print(A+B)
(A+B).sum(axis=1)

[[4 5]
 [6 7]]
[[ 6  8]
 [10 12]]


array([14, 22])

In [2]:
(A+B).sum(axis=0)

array([16, 20])